name: Run Datadog Browser Tests

on:
  push:
    branches:
      - main

jobs:
  e2e_testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Datadog Synthetic tests
        uses: DataDog/synthetics-ci-github-action@v1.13.0
        with:
          api_key: ${{ secrets.DD_API_KEY }}
          app_key: ${{ secrets.DD_APP_KEY }}
          public_ids: 'e6h-24g-w3x'
